export default function termsAndCons() {
   return (
      <div className="flex flex-col items-center justify-center w-svw text-ginaBlack">
         <div className="w-full max-w-screen-2xl items-center flex flex-col p-8">
            <div className="w-full rounded-t-3xl h-32 bg-gradient-to-r from-ginaLightYellow to-ginaOrange"></div>
            <div className="flex flex-col p-8 space-y-2">
               <h1 className="font-bold text-2xl lg:text-4xl pb-4 bg-[linear-gradient(90deg,rgba(255,209,0,1)0%,rgba(246,147,29,1)22%,rgba(0,160,75,1)78%,rgba(27,20,100,1)100%)] text-transparent bg-clip-text">
                  Gina.ph Customers Terms of Service
               </h1>
               <span className="italic">Last Updated: December 16, 2024</span>
               <p className="py-2">Thank you for booking with Gina.ph!</p>
               <p className="">
                  These Terms of Service (<span className="font-bold">“Terms”</span>) are a binding legal agreement between you and Gina.ph that govern your right to use the websites and other offerings from Gina.ph. When used in these Terms, “<span className="font-bold">Gina.ph</span>,” "<span className="font-bold">we</span>,” “<span className="font-bold">us</span>,” or “<span className="font-bold">our</span>” refers to the Gina.ph entity with whom you are contracting.
               </p>
               <p className="">
                  Gina.ph offers an online booking platform and marketplace that enables users (“<span className="font-bold">Customers</span>”) search and book experiences, tours, and other travel services. Members who publish and offer services are “<span className="font-bold">Partners</span>” and Members who search for, book, or use services are “<span className="font-bold">Customers.</span>” Partners offer (“<span className="font-bold">Accomodations</span>"), (“<span className="font-bold">Activities</span>”), (“<span className="font-bold">Tours</span>”), (“<span className="font-bold">Experiences</span>”), and a variety of (“<span className="font-bold">Travel Services</span>”) (collectively, “<span className="font-bold">Partners Services</span>,” and each Partners offering, a “<span className="font-bold">Listing</span>”). Upon booking, you must keep your information accurate. As the Partners of Gina.ph, Gina.ph does not own or control Listings or Partners Services. Gina.ph is not a party to the contracts entered into directly between Partners and Customers, nor is Gina.ph an experience or accommodation provider, travel agency, or insurer. Gina.ph is not acting as an agent in any capacity for any Customers, except as an online booking platform and marketplace.</p>
               <h2 className="text-2xl font-bold py-2">Customer Terms</h2>
               <h3 className="font-bold text-lg py-2">1. Our Mission</h3>
               <p>
                  Our mission is to enable access to new destinations and diverse experiences. We want to connect travelers and communities to make memorable travels in the country possible.</p>
               <h3 className="font-bold text-lg py-2">2. Browsing and Booking on Gina.ph.</h3>
               <p>
                  <span className="font-bold">2.1 Browsing.</span> You can search for experiences through our Facebook Page and our website. Availability can be checked by inquiring on our Facebook Page and website. Details regarding the experience and destination are included in the Facebook Post and website.</p>
               <p>
                  <span className="font-bold">2.2 Booking.</span> When you book a Listing, you are agreeing to pay all charges for your booking including the Listing price, applicable fees like bank to bank transfer and taxes and any other items identified during checkout (collectively, <span className="font-bold">“Total Price”</span>). When you receive the booking confirmation, a contract for Partners Services (a <span className="font-bold">“Reservation"</span>) is formed directly between you and the Partners. In addition to these Terms, you will be subject to, and responsible for complying with, all terms of the Reservation, including without limitation, the cancellation policy and any other rules, standards, policies, or requirements identified in the Listing or during checkout that apply to the Reservation. It is your responsibility to read and understand these rules, standards, policies, and requirements prior to booking a Listing. Be aware that some Partners work with a co-host or as part of a team to provide their Partners Services.</p>
               <p className="">
                  <span className="font-bold">2.3 Accommodation Reservations.</span> An Accommodation Reservation is a limited license to enter, occupy, and use the Accommodation. The Partners retains the right to re-enter the Accommodation during your stay, to the extent: (i) it is reasonably necessary, (ii) permitted by your contract with the Partners, and (iii) consistent with applicable law. If you stay past checkout, the Partners have the right to make you leave in a manner consistent with applicable law, including by imposing reasonable overstay penalties. You may not exceed the maximum number of paid customers.</p>
               <p className="">
                  <span className="font-bold">2.4 Reservations for Experiences and Other Partners Services.</span> An Experience or other Partners Service Reservation entitles you to participate in, attend, or use that Partners Service. You are responsible for confirming that you, and anyone you invite, meet minimum age, proficiency, fitness, or other requirements. You are responsible for informing the Partners of any medical or physical conditions, or other circumstances that may impact your ability to participate, attend, or use the Partners Service. Except where expressly authorized, you may not allow any person to join a Partners Service unless they are included as an additional customer during the booking process.</p>
               <h3 className="font-bold text-lg py-2">3. Cancellations, Travel Issues, Refunds and Booking Modifications.</h3>
               <p>
                  <span className="font-bold">3.1 Cancellations, Travel Issues, and Refunds.</span> In general, if as a Customer you cancel a Reservation, the amount refunded to you is 80% of the total cost of the booking or Reservation. But, in certain situations, other policies take precedence and determine what amount is refunded to you. If something outside your control forces you to cancel a Reservation, you may be eligible for a partial refunded. If the Partners cancels, or you experience a Travel Issue, you may be eligible for rebooking assistance or a partial refund.</p>
               <p>
                  <span className="font-bold">3.2 Booking Modifications.</span> Customers and Partners are responsible for any booking modifications they agree to make via the Gina.ph platform or direct Gina.ph customer service to make on their behalf ("<span className="font-bold">Booking Modifications</span>"), and agree to pay any additional amounts, fees, or taxes associated with any Booking Modification.</p>
               <h3 className="font-bold text-lg py-2">4. Your Responsibilities and Assumption of Risk.</h3>
               <p>
                  <span className="font-bold">4.1 Your Responsibilities.</span> You are responsible and liable for your own acts and omissions and are also responsible for the acts and omissions of anyone you invite to join or provide access to any Accommodation, Experience or other Partners Service. For example, this means: (i) you are responsible for leaving an Accommodation (and related personal property) in the condition it was in when you arrived, (ii) you are responsible for paying all reasonable Damage Claim amounts necessary to cover damage that you, your companion(s), or your pet(s) cause to an Accommodation, and (iii) you must act with integrity, treat others with respect, and comply with applicable laws at all times. If you are booking for an additional client who is a minor or if you bring a minor to a Partners Service, you must be legally authorized to act on behalf of the minor and you are solely responsible for the supervision of that minor.</p>
               <p>
                  <span className="font-bold">4.2 Your Assumption of Risk.</span> You acknowledge that many activities carry inherent risks and agree that, to the maximum extent permitted by applicable law, you assume the entire risk arising out of your access to and use of the Gina.ph platform and any Content, including your stay at any Accommodation, participation in any Experience, use of any other Partners Service, or any other interaction you have with other Members whether in person or online. This means it is your responsibility to investigate a Partners Service to determine whether it is suitable for you. For example, Partners Services may carry risk of illness, bodily injury, disability, or death, and you freely and willfully assume those risks by choosing to participate in those Partners Services.</p>
            </div>
         </div>
      </div>
   );
}
